name: application_insights_js
description: "A Dart wrapper for the Microsoft Application Insights JavaScript SDK."
version: 0.3.0
homepage: https://github.com/milestonetg/application-insights-js-dart

authors:
- Ethan Lafrenais <ethan.lafrenais@milestonetg.com>

# Not ready for publishing yet
publish_to: none

environment:
  sdk: ">=1.23.0 <3.0.0"
